# permissions for end users to view managedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedcluster-viewer-role
rules:
- apiGroups:
  - cluster.security.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.security.io
  resources:
  - managedclusters/status
  verbs:
  - get
